spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL} # 환경 변수로 주입
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
logging:
  level:
    com.laze.batch: DEBUG # dev 환경 로그 레벨
    org.springframework.batch: DEBUG
