spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
logging:
  level:
    com.laze.batch: DEBUG
#    org.springframework.batch: DEBUG
    # --- !!! Spring Batch 및 관련 자동 설정 로그 레벨 TRACE 로 변경 !!! ---
    org.springframework.batch: TRACE
    org.springframework.boot.autoconfigure.batch: TRACE
    # CommandLineJobRunner 클래스 (정식 이름은 JobLauncherApplicationRunner) 로그도 확인
    org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner: TRACE
