server:
  port: 9001
spring:
  application:
    name: web-framework-backend
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
logging:
  level:
    root: INFO
    com.laze.backend: INFO
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
#
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: Web Framework API
    version: 1.0.0
    description: 프레임워크 API 문서
  servers:
    - url: <http://localhost:9001>
      description: Local Server
