server:
  port: 9001
spring:
  application:
    name: web-framework-backend
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
logging:
  level:
    root: INFO
    com.laze.backend: INFO
