spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL} # 기본값: 로컬 설치 DB 예시
    username: ${SPRING_DATASOURCE_USERNAME} # 기본값: 로컬 설치 DB 사용자 예시
    password: ${SPRING_DATASOURCE_PASSWORD} # !!! 비밀번호는 환경 변수로 주입 필수 (기본값 없음) !!!
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
logging:
  level:
    com.laze.backend: DEBUG
    org.mybatis: TRACE
    org.springframework.security: TRACE
